"""Refactored models

Revision ID: 32b20231b4d4
Revises: 61e622e2e8ad
Create Date: 2024-12-04 15:55:38.308421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b20231b4d4'
down_revision = '61e622e2e8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_children', schema=None) as batch_op:
        batch_op.drop_constraint('family_children_child_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('family_children_family_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'individuals', ['child_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'families', ['family_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_children', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('family_children_family_id_fkey', 'families', ['family_id'], ['id'])
        batch_op.create_foreign_key('family_children_child_id_fkey', 'individuals', ['child_id'], ['id'])

    # ### end Alembic commands ###
