"""Update GenderEnum

Revision ID: 61e622e2e8ad
Revises: 9d7cd69f3d07
Create Date: 2024-12-04 15:12:54.632584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61e622e2e8ad'
down_revision = '9d7cd69f3d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'TRANSGENDER', 'GENDER_NEUTRAL', 'NON_BINARY', 'AGENDER', 'PANGENDER', 'GENDERQUEER', 'TWO_SPIRIT', 'THIRD_GENDER', 'OTHER', 'UNKNOWN', name='genderenum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'TRANSGENDER', 'GENDER_NEUTRAL', 'NON_BINARY', 'AGENDER', 'PANGENDER', 'GENDERQUEER', 'TWO_SPIRIT', 'THIRD_GENDER', 'OTHER', 'UNKNOWN', name='genderenum'),
               nullable=True)

    # ### end Alembic commands ###
