"""Allow partner2_id to be nullable in families

Revision ID: 9d7cd69f3d07
Revises: 23e35f81ed91
Create Date: 2024-12-03 21:17:57.341302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7cd69f3d07'
down_revision = '23e35f81ed91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.alter_column('partner2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('uix_partners', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_partners', ['partner1_id', 'partner2_id'])
        batch_op.alter_column('partner2_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
