from .auth import web_auth_bp
from .citations import web_citations_bp
from .custom_enums import web_custom_enums_bp
from .custom_fields import web_custom_fields_bp
from .events import web_events_bp
from .families import web_families_bp
from .identities import web_identities_bp
from .individuals import web_individuals_bp
from .main import web_main_bp
from .profile import web_profile_bp
from .projects import web_projects_bp
from .sources import web_sources_bp
